# Generated by Django 4.2.1 on 2023-05-28 15:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cam', '0002_remove_user_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='VehiclePost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('text', models.TextField()),
                ('published', models.DateTimeField(auto_now_add=True, verbose_name='post date')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='cam.vehicle')),
            ],
        ),
    ]
