# Generated by Django 4.2.1 on 2023-05-28 16:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cam', '0004_alter_attendsevent_user_alter_coffee_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='published',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='post date'),
            preserve_default=False,
        ),
    ]
