# Generated by Django 4.2.1 on 2023-05-28 16:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cam', '0005_vehicle_published'),
    ]

    operations = [
        migrations.CreateModel(
            name='CofComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('published', models.DateTimeField(auto_now_add=True, verbose_name='comment date')),
            ],
        ),
        migrations.CreateModel(
            name='CofReply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('published', models.DateTimeField(auto_now_add=True, verbose_name='reply date')),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cam.cofcomment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='VehComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('published', models.DateTimeField(auto_now_add=True, verbose_name='comment date')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cam.vehicle')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='VehReply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('published', models.DateTimeField(auto_now_add=True, verbose_name='reply date')),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cam.vehcomment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='post',
            name='user',
        ),
        migrations.RemoveField(
            model_name='reply',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='reply',
            name='user',
        ),
        migrations.RemoveField(
            model_name='vehiclepost',
            name='vehicle',
        ),
        migrations.AddField(
            model_name='coffee',
            name='published',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='post date'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
        migrations.DeleteModel(
            name='Post',
        ),
        migrations.DeleteModel(
            name='Reply',
        ),
        migrations.DeleteModel(
            name='VehiclePost',
        ),
        migrations.AddField(
            model_name='cofcomment',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cam.coffee'),
        ),
        migrations.AddField(
            model_name='cofcomment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
