# Generated by Django 4.2.1 on 2023-05-28 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cam', '0006_cofcomment_cofreply_vehcomment_vehreply_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cofcomment',
            name='text',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='cofreply',
            name='text',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='vehcomment',
            name='text',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='vehreply',
            name='text',
            field=models.CharField(max_length=100),
        ),
    ]
