# Generated by Django 4.2.1 on 2023-05-28 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cam', '0008_event_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='image',
            field=models.ImageField(default='null', upload_to='upload/'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='VehReply',
        ),
    ]
