# Generated by Django 4.2.1 on 2023-05-28 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cam', '0009_vehicle_image_delete_vehreply'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='image',
            field=models.ImageField(upload_to='static/'),
        ),
    ]
